const data = [
  {
    id:'1',
    img:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
    name:'bulbasaur',
    types:[
      'grass',
      'poison'
    ],
    link:'https://pokeapi.co/api/v2/pokemon/1/'
  },
  {
    id:'2',
    img:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png',
    name:'Ivysaur',
    types:[
      'grass',
      'poison'
    ],
    link:'https://pokeapi.co/api/v2/pokemon/2/'
  },
  {
    id:'3',
    img:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    name:'Venusaur',
    types:[
      'grass',
      'poison'
    ],
    link:'https://pokeapi.co/api/v2/pokemon/3'
  },
  {
    id:'4',
    img:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
    name:'Charmander',
    types:[
      'fire'
    ],
    link:'https://pokeapi.co/api/v2/pokemon/4/'
  },
  {
    id:'5',
    img:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png',
    name:'Chameleon',
    types:[
      'fire'
    ],
    link:'https://pokeapi.co/api/v2/pokemon/5/'
  },
  {
    id:'6',
    img:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
    name:'Charizard',
    types:[
      'fire',
      'flying'
    ],
    link:'https://pokeapi.co/api/v2/pokemon/6/'
  },
  {
    id:'151',
    img:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png',
    name:'Mew',
    types:[
      'Psychic',
    ],
    link:'https://pokeapi.co/api/v2/pokemon/151/'
  },
]

export default data;